apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: star-wars-api-deployment
spec:
  selector:
    matchLabels:
      app: star-wars-api
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: star-wars-api
    spec:
      containers:
      - name: star-wars-api
        image: wluindayk/star-wars-api:0.0.1
        ports:
        - containerPort: 9000
